env: 'dev'
external_api: "http://localhost:8081"
http_server:
  port: ":8080"
database:
  db_port: "5432"
  db_host: "localhost"
  db_name: "test-api"
  db_username: "postgres"
  db_password: "postgres"
  ssl_mode: "disable"